name: Linters

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

        # NOTE: Required by `gitleaks` pre-commit hook
      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.26.3"

      - name: Set up Hadolint
        shell: bash
        working-directory: ${{ runner.temp }}
        env:
          HADOLINT_VERSION: 2.14.0
          HADOLINT_PKG_NAME: "hadolint-linux-x86_64"
          HADOLINT_PKG_SHA256: "6bf226944684f56c84dd014e8b979d27425c0148f61b3bd99bcc6f39e9dc5a47"
        run: |
          echo "Download and verify Package"
          curl -fsSLO https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/${HADOLINT_PKG_NAME}
          echo "${HADOLINT_PKG_SHA256} ${HADOLINT_PKG_NAME}" | sha256sum --check
          sudo mv ${HADOLINT_PKG_NAME} /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint
          if ! command -v hadolint &> /dev/null; then
            echo "ERROR: Hadolint installation completed but the command is not available"
            exit 1
          fi

      - name: Run prek (pre-commit)
        uses: j178/prek-action@6ad80277337ad479fe43bd70701c3f7f8aa74db3 # v2.0.3
